using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BuildingExitCollider : MonoBehaviour
{
    public Building building;
    bool already = false;
    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.layer == LayerMask.NameToLayer("Player"))
        {
            if (!already)
            {
                Invoke(nameof(alreadyDisabler), 0.5f);
                already = true;
                building.PlayerExitedfromBuilding = true;
            }
        }
        
    }
    void alreadyDisabler()
    {
        already = false; 
    }
}
