using UnityEngine;
using CnControls;
public class RocketMovement : MonoBehaviour
{
    public static RocketMovement Instance;
    public float speed;
    float newHorPos= 0f;
    float newVerPos= 0f;
    private void Awake()
    {
        Instance = this;
    }
    private void Start()
    {
        GameManager.DifficultyIncreased.AddListener(() => SpeedIncreaser());
    }
    void FixedUpdate()
    {
        // Move the rocket upward
        newHorPos = Mathf.Lerp(newHorPos ,CnInputManager.GetAxis("Horizontal"),Time.deltaTime);
        newVerPos = Mathf.Lerp(newVerPos, CnInputManager.GetAxis("Vertical"),Time.deltaTime);
        transform.position=new Vector3(newHorPos, transform.position.y, -newVerPos);
        transform.Translate(Vector3.up * speed * Time.deltaTime );
    }
    void SpeedIncreaser()
    {
        speed += 0.5f;
    }
}
