using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using UnityEngine.SceneManagement;
public class UIManager : MonoBehaviour
{
    public TextMeshProUGUI Health;
    public static UIManager instance;
    public CharacterController player;
    public GameObject GameOverPanel;
    public CameraFollow cameraFollow;
    private void Awake()
    {
        instance = this;
    }
    private void Start()
    {
        UpdateHealth();
    }
    public void UpdateHealth()
    {
        Health.text = "Health: " + player.Health.ToString();
        if (player.Health <= 2)
        {
            GameOver();
        }
    }
    void GameOver()
    {
        player.SpineHingeJoint.connectedBody = null;
        cameraFollow.isPlaying = false;
    }
    public void Restart()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }
}
