using UnityEngine;

public class RocketMovement : MonoBehaviour
{
    public float speed = 5f;
    float newHorPos= 0f;
    float newVerPos= 0f;

    void Update()
    {
        // Move the rocket upward
        newHorPos = Mathf.Lerp(newHorPos ,Input.GetAxis("Horizontal"),Time.deltaTime);
        newVerPos = Mathf.Lerp(newVerPos, Input.GetAxis("Vertical"),Time.deltaTime);
        transform.position=new Vector3(newHorPos, transform.position.y, -newVerPos);
        transform.Translate(Vector3.up * speed * Time.deltaTime );
    }
}
