using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ObstacleHitReceiver : MonoBehaviour
{
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.layer == LayerMask.NameToLayer("Player"))
        {
            UIManager.instance.player.Health -= Random.Range(1,5);
            UIManager.instance.UpdateHealth();
        }
    }
    private void OnCollisionStay(Collision collision)
    {
        //if (collision.gameObject.layer == LayerMask.NameToLayer("Player"))
        //{
        //    UIManager.instance.player.Health -= Random.Range(1, 5);
        //    UIManager.instance.UpdateHealth();
        //}
    }
}
